# Generated by Django 4.0.2 on 2022-04-15 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='Menu',
            new_name='menu',
        ),
    ]
