# Generated by Django 4.0.3 on 2022-04-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0004_restaurant_slug_alter_restaurant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='slug',
        ),
    ]
